baseURL = "https://xxac.net"
title = "Xxac Industries"
author = "X001"
copyright = "© 2808, Xxac Industries Limited"

theme = "risotto"
paginate = 3

languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

# automatically add content sections to main menu
#sectionPagesMenu = "main"

[permalinks]
  entries = '/:sections/:year/:yearday'

[params]

  [params.theme]
    palette = "xxac-dark"
    mode = "dark-mode"

  [params.about]
    title = "Drone Ops Terminal"
    description = "DroneOps 18.04 LTS (drone-term 5.0.4 x86_64)"
    logo = "icon.svg"

[menu]

  [[menu.main]]
    identifier = "motd"
    name = "motd"
    url = "/motd/"
    weight = 10

  [[menu.main]]
    identifier = "employees"
    name = "Employees"
    url = "/employees/"
    weight = 11

  [[menu.main]]
    identifier = "entries"
    name = "log_entries"
    url = "/entries/"
    weight = 12

[taxonomies]
  tag = "tags"
  employee = "employees"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
  unsafe = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true